name: Check Broken Links

on:
  workflow_dispatch: # Manual trigger

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --exclude-mail --exclude "https://example.com" .
          fail: true # Fail the workflow if broken links are found
          output: lychee-report.txt # Save the output to a file

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: broken-links-report
          path: lychee-report.txt
