name: Check Broken Links

on:
  workflow_dispatch: # Manual trigger

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install -g cypress cypress-broken-link-checker

      - name: Run Cypress Broken Link Checker
        run: |
          cypress-broken-link-checker --url "https://portfolio-devadula-nandan.vercel.app/" --exclude "mailto:*" --recursive

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: broken-links-report
          path: cypress-broken-links-report.json
